services:
  apache:
    image: ghcr.io/ifpb/new_wave/wave-apache
    container_name: server
    #ports:
    #- "80:80"

  client_container:
    image: ghcr.io/ifpb/new_wave/wave-vlc
    container_name: client
    privileged: true
    #environment:
      #- DISPLAY=${DISPLAY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/home/vlc/logs
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - apache
